name: Run Cypress Tests

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - uses: cypress-io/github-action@v2
        with:
          start: npm run dev
          command: npm run test:cypress:integration
        env:
          CYPRESS_baseUrl: http://localhost:3000
