name: Run Cypress Tests

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1

      - name: Build
        run: |
          npm ci
          npm run dev

      - uses: cypress-io/github-action@v2
        with:
          browser: chrome
          headless: true
          working-directory: e2e
